### ISSUE TITLE
Not getting access to weights

### ISSUE THREAD

**Issue by ahmedivy** [meta-llama/llama#1012]
I submitted the form to access Llama2 weights on the day Meta released it. However, up until now, I have not received any email. I have filled out the form multiple times, but there has been no response on each occasion. Are there any eligibility criteria for this?

**Comment by samuelselvan** [comment]
@ahmedivy - can you share the request id you get when you submit the access request?

**Comment by ahmedivy** [comment]
> @ahmedivy - can you share the request id you get when you submit the access request?

I didn't notice that. So I filled the form again and here it is.

Request ID: 1562861604513666

**Comment by mr-gorjan** [comment]
Same here
Request ID - 1082779639590404

Also on HuggingFace, it says "Your request to access this repo has been successfully submitted, and is pending a review from the repo's authors."

@samuelselvan

**Comment by ahmedivy** [comment]
Any news @samuelselvan ? 🥲

**Comment by samuelselvan** [comment]
@ahmedivy / @mr-gorjan  - am working internally to correct this. Will get back.

**Comment by mr-gorjan** [comment]
![1](https://github.com/facebookresearch/llama/assets/19906409/9163f8da-78b2-4eee-8123-f3c4937a16f8)

**Comment by sidbnoida** [comment]
I have filled the form but did not see any request id. Only the following image
<img width="733" alt="image" src="https://github.com/facebookresearch/llama/assets/132843097/fa6107e3-d92b-4083-848b-26bd499af6c5">

**Comment by sidbnoida** [comment]
Also havent recieved any email since days...Please help.

**Comment by kessleron** [comment]
I lost my patience at some point

**Comment by mr-gorjan** [comment]
![1](https://github.com/facebookresearch/llama/assets/19906409/410c8f09-859d-4c4e-a533-06b11629fd4e)

**Comment by samuelselvan** [comment]
All, could you please re-request and provide the request id?
