### ISSUE TITLE
Llama local download : download.sh: line 19: wget: command not found

### ISSUE THREAD

**Issue by Hannan1002** [meta-llama/llama#1025]
$ bash download.sh
Enter the URL from email: ```Entered the address from the gmail```
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 70B-chat
Downloading LICENSE and Acceptable Usage Policy
download.sh: line 19: wget: command not found

**Comment by ManuThakur10** [comment]
Also having this issue!

**Comment by ManuThakur10** [comment]
> Also having this issue!

I fixed it; thread #833 covers a solution. 
Basically, to install wget properly, use homebrew instead: `brew install wget`

**Comment by liqing-lau** [comment]
if you're using windows, thread #715 talks about using an updated wget version

**Comment by SergheiDinu** [comment]
i use conda on m1 mac and "conda install wget" worked for me

**Comment by Morrisvdb** [comment]
For me running `bash download.sh` in CMD instead did the trick
