### ISSUE TITLE
Having trouble downloading the model

### ISSUE THREAD

**Issue by QHX1998** [meta-llama/llama#1035]
I tried to run download.sh and entered the url given in the email sent for LLama 2 (I checked it)

Then after I choose the model ( I decide to download all models so I just press the enter ), it quickly showed some message and then closed itself.

This is the last thing I can screenshot:

![微信图片_20240223140838](https://github.com/facebookresearch/llama/assets/51979105/2eb6af0c-9bc2-4312-9cae-3bbc8bb4dd2b)

I don't know why and it seems that no model is downloaded.

**Comment by samuelselvan** [comment]
@QHX1998 can you give your `wget` version. Usually this error goes away when you upgrade, which you can give a try as well.

Also what OS are you oon?

**Comment by VamsiKrishnaNori** [comment]
https://github.com/meta-llama/llama/issues/402#issuecomment-2016857251

Please check out this solution

**Comment by samuelselvan** [comment]
Please follow what @VamsiKrishnaNori had suggested, if any issue still let us know.
