### ISSUE TITLE
Removing usage of open source

### ISSUE THREAD

**Issue by patrick-fitzgerald** [meta-llama/llama#1047]
Hi, 
I see this [issue](https://github.com/facebookresearch/llama/issues/440) was raised previously, but it did not specifically address if the Llama [license](https://github.com/facebookresearch/llama/blob/main/LICENSE) is compliant with the OSI's definition of "open source".
The OSI does not agree with the use of "open source" by this project: https://opensource.org/blog/metas-llama-2-license-is-not-open-source
Is there plans to remove the term `Llama 2: open source` from the website? To reduce the threat of legal action. e.g https://www.theregister.com/2022/03/17/court_open_source/

Thanks

**Comment by jspisak** [comment]
HI there - we've actually worked with the OSI folks to update definitions. 

You can see the details here: https://hackmd.io/@opensourceinitiative/osaid-0-0-6#

Cheers..

**Comment by Edmartt** [comment]
> HI there - we've actually worked with the OSI folks to update definitions. 
> 
> You can see the details here: https://hackmd.io/@opensourceinitiative/osaid-0-0-6#
> 
> Cheers..

So, you want to update the definition and not your license, right? Llama is not open source, we have no access of every aspect. Sorry not to sorry.
