### ISSUE TITLE
download.sh in Kaggle 

### ISSUE THREAD

**Issue by chaojiang-777** [meta-llama/llama#1052]
![image](https://github.com/facebookresearch/llama/assets/159562295/012ff3de-0db1-444f-8401-fb39e8db7711)

Hi,  When I input download.sh in kaggle, I cannot find any input cell, could anyone give me some tips?

Best

**Comment by WuhanMonkey** [comment]
Hi @chaojiang-777, this seems like an issue on Kaggle notebooks that you need to talk to them. What we provided is a just a standard shell scripts for download.
