### ISSUE TITLE
How to solve it? I just can't use demo of llama-7B 

### ISSUE THREAD

**Issue by handicaps** [meta-llama/llama#1065]
torchrun --nproc_per_node 1 example_text_completion.py \     --ckpt_dir llama-2-7b/ \     --tokenizer_path tokenizer.model \     --max_seq_len 128 --max_batch_size 6

here is the information:

> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loaded in 12.54 seconds
Traceback (most recent call last):
  File "example_text_completion.py", line 69, in <module>
    fire.Fire(main)
  File "/root/miniconda3/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example_text_completion.py", line 56, in main
    results = generator.text_completion(
  File "/root/llama/llama/generation.py", line 265, in text_completion
    generation_tokens, generation_logprobs = self.generate(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/llama/llama/generation.py", line 165, in generate
    total_len = min(params.max_seq_len, max_gen_len + max_prompt_len)
TypeError: can only concatenate str (not "int") to str
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2154) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-14_22:12:30
  host      : autodl-container-fd5346abcb-531ea3c8
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2154)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by jiehai4** [comment]
老哥，你解决了吗？

**Comment by handicaps** [comment]
解决llama2-7B-chat模型使用demo时，报错“TypeError: can only concatenate str (not "int") to str”的问题 - 简书 (jianshu.com)这个是我前面写的总结，如果你还没解决的话可以参考一下
&nbsp;


2665038949
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月30日(星期二) 晚上7:07
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [meta-llama/llama] How to solve it? I just can&#39;t use demo of llama-7B  (Issue #1065)














 
老哥，你解决了吗？

**Comment by jiehai4** [comment]
世界真小啊，在逛GitHub之前我也拿bing搜索过，找到了这个解决方案，这就看见作者了。能给我一个微信号加个微信吗？毕竟我感觉你也是学生，就是不知道是本科还是研究生。
很感谢你的解决方案，事实证明它是有用的。
话说你知道.gguf如何本地部署成咱们那种应答形式吗？之前搞llama3，但是llama3在 bash download.sh那里输入URL只会返回403（刚申请的URL也不行），现在只在网上找到了gguf的版本，想看看有没有办法得到可运行的结果


潘星晔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meta-llama/llama"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月1日(星期三) 凌晨0:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meta-llama/llama] How to solve it? I just can't use demo of llama-7B  (Issue #1065)





 解决llama2-7B-chat模型使用demo时，报错“TypeError: can only concatenate str (not "int") to str”的问题 - 简书 (jianshu.com)这个是我前面写的总结，如果你还没解决的话可以参考一下 
 &amp;nbsp; 
 
 
 2665038949 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2024年4月30日(星期二) 晚上7:07 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.******@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [meta-llama/llama] How to solve it? I just can&amp;#39;t use demo of llama-7B  (Issue #1065) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
   
 老哥，你解决了吗？

**Comment by handicaps** [comment]
llama3的话应该huggingface上面的版本比较好部署，官网的我没成功过。微信的话:taste_spring


---Original---
From: ***@***.***&gt;
Date: Wed, May 1, 2024 17:48 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;&quot;State ***@***.***&gt;;
Subject: Re: [meta-llama/llama] How to solve it? I just can't use demo ofllama-7B  (Issue #1065)




 世界真小啊，在逛GitHub之前我也拿bing搜索过，找到了这个解决方案，这就看见作者了。能给我一个微信号加个微信吗？毕竟我感觉你也是学生，就是不知道是本科还是研究生。 
 很感谢你的解决方案，事实证明它是有用的。 
 话说你知道.gguf如何本地部署成咱们那种应答形式吗？之前搞llama3，但是llama3在 bash download.sh那里输入URL只会返回403（刚申请的URL也不行），现在只在网上找到了gguf的版本，想看看有没有办法得到可运行的结果 
 
 
 潘星晔 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        &quot;meta-llama/llama&quot;                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年5月1日(星期三) 凌晨0:39 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [meta-llama/llama] How to solve it? I just can&#39;t use demo of llama-7B  (Issue #1065) 
 
 
 
 
 
  解决llama2-7B-chat模型使用demo时，报错“TypeError: can only concatenate str (not &quot;int&quot;) to str”的问题 - 简书 (jianshu.com)这个是我前面写的总结，如果你还没解决的话可以参考一下  
  &amp;amp;nbsp;  
   
   
  2665038949  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2024年4月30日(星期二) 晚上7:07  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.******@***.***&amp;amp;gt;; &quot;State ***@***.***&amp;amp;gt;;   
  主题: Re: [meta-llama/llama] How to solve it? I just can&amp;amp;#39;t use demo of llama-7B  (Issue #1065)  
   
   
   
   
   
   
   
   
   
   
   
   
   
   
     
  老哥，你解决了吗？  
     
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
&mdash;
