### ISSUE TITLE
403 Forbidden, after downloading 96%

### ISSUE THREAD

**Issue by jkwiatk1** [meta-llama/llama#1070]
## Describe the bug
Hello, while downloading llama-2-7b after downloading 96% I got an error pop up:

```
Connecting to download.llamameta.net (download.llamameta.net)|13.32.121.120|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden.
2024-03-16 15:59:37 ERROR 403: Forbidden..
```

With the first link generated, the download didn't start at all until the second time but after downloading 96% the problem occurred again.

Should I generate the link again? 

## Runtime Environment
- Model: [`llama-2-7b`,`llama-2-7b-chat`]
- Using via huggingface?: [yes]
- OS: [Windows]
- GPU VRAM: 4GB
- Number of GPUs: 1
- GPU Make: [eg: Nvidia]
- RAM: 16GB

**Comment by samuelselvan** [comment]
@jkwiatk1 please retry and re-open if you still face issues.
