### ISSUE TITLE
Prompt template for finetuning on text summaraization/generation

### ISSUE THREAD

**Issue by smreddy05** [meta-llama/llama#1074]
I am using following prompt template for my fine-tuning activities.
---

```{r}

<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>

{{ user_message }} [/INST]
 """

is it okay to use this for non-chat application purposes? will this template make model to remember the previous inputs and outputs?

**Comment by jspisak** [comment]
@wuhanmonkey

**Comment by WuhanMonkey** [comment]
Hi @smreddy05, the special tokens here [INST] specifically kick the model into chat mode. So it is for chat application. Also Llama 2 as a model is stateless, so there is memory of the model or the model will not remember what the previous input or context was. There are numerous examples on how to build memory for chatbots with Llama, please search on the internet. Closing.

**Comment by smreddy05** [comment]
@WuhanMonkey  so is it advisable to use this format if my use case is for text generation or question/answering? or better to stick with other formats like
```{r}
### Instruction:

### input:
{sample['input']}

### outputs:
{sample['output']}

**Comment by smreddy05** [comment]
@WuhanMonkey  can you please help us on this?

**Comment by arktrail** [comment]
@smreddy05 Yes It is actually find to write the prompt using the format like this. And actually using the special splitter like ### is a recommended way which provides a clear schema for model to follow.

**Comment by smreddy05** [comment]
Thanks  @arktrail
