### ISSUE TITLE
Not getting access to Llama2 and Llama3

### ISSUE THREAD

**Issue by ahmedivy** [meta-llama/llama#1134]
I am not getting access to download Meta Llama2 and Llama3, I submitted request in early days when Llama2 was released and on the first day of Llama3 release, but still didn't got approval. 

I already opened an issue #1012 , but after 6 months of wait @samuelselvan closed it without resolving.

I requested both from Meta Website and HuggingFace.

### HuggingFace Screenshot:
<img width="750" alt="image" src="https://github.com/meta-llama/llama/assets/91587113/c7f791b6-1cf2-407d-bb8f-8ebeb3bece36">

**Comment by ahmedivy** [comment]
Now if I request again at meta [website](https://llama.meta.com/llama-downloads) , I got following error:

> Sorry, we could not process your request at this moment. Request ID: 475679205108877

**Comment by amaanaijazsheikh** [comment]
Hey, were you able to get this resolved?
I am also facing the same issue

**Comment by ahmedivy** [comment]
> Hey, were you able to get this resolved?
> I am also facing the same issue
> 

Yes, after opening this issue, they approved my both requests immediately but no one replied here so I closed the issue.
