### ISSUE TITLE
Your request to access this repo has been rejected by the repo's authors. 

### ISSUE THREAD

**Issue by wingchi-leung** [meta-llama/llama#1136]
**Before submitting a bug, please make sure the issue hasn't been already addressed by searching through the [FAQs](https://ai.meta.com/llama/faq/) and [existing/past issues](https://github.com/facebookresearch/llama/issues)**

## Describe the bug
I am applying to get access meta-llama/Llama-2-7b at Huggingface but after I submit my application I got a reject "Your request to access this repo has been rejected by the repo's authors." , I don't know why and  how to fix this. can any body explain why I got rejected and may be reapply again ?

**Comment by LexusShabunya** [comment]
I am applying to get access meta-llama/Llama-2-7b-chat-hf at Huggingface but after I submit my application I got a reject "Your request to access this repo has been rejected by the repo's authors." , I don't know why and how to fix this. Can any body explain why I got rejected and may be reapply again? My Huggingface account: LexusShabunya

**Comment by Mizar77** [comment]
I am applying to get access meta-llama/Llama-2-7b-chat-hf at Huggingface but after I submit my application I got a reject "Your request to access this repo has been rejected by the repo's authors." , I don't know why and how to fix this. Can any body explain why I got rejected and may be reapply again? My Huggingface account: Mizar0

**Comment by yijiangqingfeng** [comment]
I am applying to get access meta-llama/Llama-2-7b-chat-hf at Huggingface but after I submit my application I got a reject "Your request to access this repo has been rejected by the repo's authors." , I don't know why and how to fix this. Can any body explain why I got rejected and may be reapply again? My Huggingface account: yijiangqingfeng
