### ISSUE TITLE
A problem with tokenizer.model from HuggingFace

### ISSUE THREAD

**Issue by vintoniuk** [meta-llama/llama#1151]
## Describe the bug
I downloaded the checkpoint of [Meta-Llama-3.1-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct) from HuggingFace to use with the raw model code from the [current repository](https://github.com/meta-llama/llama). However, when I try to load the tokenizer from the provided `tokenizer.model` file, the following error is raised. I tried it in a completely clean environment in the cloud running Ubuntu as well as on my PC running Windows.

There is also a similar [issue](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/discussions/109) on HuggingFace, though pretty old one.

### Minimal reproducible example

```python
from llama import Tokenizer
tokenizer = Tokenizer('/home/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model')
```

### Output

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[7], line 2
      1 from llama import Tokenizer
----> 2 tokenizer = Tokenizer('/home/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model')

File /home/analysis/llama/tokenizer.py:25, in Tokenizer.__init__(self, model_path)
     23 # reload tokenizer
     24 assert os.path.isfile(model_path), model_path
---> 25 self.sp_model = SentencePieceProcessor(model_file=model_path)
     26 logger.info(f"Reloaded SentencePiece model from {model_path}")
     28 # BOS / EOS token IDs

File /opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py:468, in SentencePieceProcessor.Init(self, model_file, model_proto, out_type, add_bos, add_eos, reverse, emit_unk_piece, enable_sampling, nbest_size, alpha, num_threads)
    466 self._num_threads = num_threads
    467 if model_file or model_proto:
--> 468   self.Load(model_file=model_file, model_proto=model_proto)

File /opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py:961, in SentencePieceProcessor.Load(self, model_file, model_proto)
    959 if model_proto:
    960   return self.LoadFromSerializedProto(model_proto)
--> 961 return self.LoadFromFile(model_file)

File /opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py:316, in SentencePieceProcessor.LoadFromFile(self, arg)
    315 def LoadFromFile(self, arg):
--> 316     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)

RuntimeError: Internal: could not parse ModelProto from /home/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
```

## Runtime Environment
- Model: `llama-3.1-8B-instruct`
- Using via huggingface?: yes
- OS: Linux/Ubuntu
- GPU VRAM: 46080 MiB
- Number of GPUs: 1
- GPU Make: Nvidia

**Additional context**

To download the checkpoint:
`huggingface-cli download meta-llama/Meta-Llama-3.1-8B-Instruct --include "original/*" --local-dir Meta-Llama-3.1-8B-Instruct`

**Comment by MaheshKumar92** [comment]
+1

**Comment by vintoniuk** [comment]
Hi, @MaheshKumar92! The problem is that this repository is outdated and uses SentencePiece tokenizer, but Llama 3.1 uses Tiktoken tokenizer, so the `tokenizer.model` file is not recognized. Use [the new repository](https://github.com/meta-llama/llama-models) and choose the appropriate inference code from `/models` folder.
