### ISSUE TITLE
Shell Command in README.md example

### ISSUE THREAD

**Issue by aAnubhav2147** [meta-llama/llama#460]
Hi,

   I was trying to run the pre-trained & fine-tuned examples in the README. During this, I noticed that the code block was missing an '!'. I'd request the admins update the code block to reflect that it is a shell command rather than Python code. It's a minor issue, but it can trip people up, especially beginners like me.
  
 In summary, this:
 
 `torchrun --nproc_per_node 1 example_chat_completion.py \
    --ckpt_dir llama-2-7b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 4`
    
  Should be this:
  
  `!torchrun --nproc_per_node 1 example_chat_completion.py \
    --ckpt_dir llama-2-7b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 4`
    
   I hope this was helpful.

Thank You.

Regards,
Anubhav Shankar

**Comment by apurvagandhi** [comment]
Can I fix this issue? 
!assign

**Comment by aAnubhav2147** [comment]
Sure. Let me assign it to you.

**Comment by jvgimenes** [comment]
Hi all, I see this issue is still opened so I took the liberty of opening a PR with the suggested change.

**Comment by artiebits** [comment]
The `!` symbol is not needed to run `torchrun` from a terminal.
