### ISSUE TITLE
The way to download the model weight is wrong

### ISSUE THREAD

**Issue by ADaBenxiong** [meta-llama/llama#716]
When I want to download the model weight, I login the "https://ai.meta.com/". However I can not to download the model, where shows "Sorry, the download is not available in your region."
What is the wrong

**Comment by lmarcon** [comment]
Does this url works for you? https://ai.meta.com/resources/models-and-libraries/llama-downloads/

**Comment by WuhanMonkey** [comment]
@ADaBenxiong Did you make official request to download the weights from the website?

**Comment by linrl3** [comment]
Same for me. I access https://ai.meta.com/resources/models-and-libraries/llama-downloads/ from China. It shows "Sorry, the download is not available in your region."

**Comment by karanotsingyu** [comment]
@linrl3 您好，请问您现在解决这个问题了吗。我也遇到了这条 “Sorry” ；即便全局、换节点再换个浏览器也如此。
