### ISSUE TITLE
every time I enter the link from my email and select my midel i get "download.sh: line 19: wget: command not found"

### ISSUE THREAD

**Issue by jack152907** [meta-llama/llama#833]
Sorry, trying to figure this out while being new here. Any help would be great.

**Comment by sergeiGKS** [comment]
You need to install wget in your working environment. 

I got the same issue on Windows using Git Bash

Here are the steps to solve the issue:

1. Dowload wget.exe file from this link [https://eternallybored.org/misc/wget/](https://eternallybored.org/misc/wget/)
2. Install wget
3. Copy the wget.exe file to git bash binaries folder e.g. "C:\Program Files\Git\mingw64\bin"

**Comment by jspisak** [comment]
@jack152907 - let us know if this solves your issue and we can close this one while updating our docs. cc @samuelselvan

**Comment by samuelselvan** [comment]
@cclemon2143 - if you have brew can you try and install via `brew install wget`

@jack152907 are you using macOS as well?

**Comment by cclemon2143** [comment]
@samuelselvan I try to install brew and use it install wget, it's work!!

**Comment by cclemon2143** [comment]
But after I install the llama 2 7B model, And running the model, it show NOTE: no support Windows and MacOS....

**Comment by samuelselvan** [comment]
@cclemon2143 - can you share more details of what you are seeing?

**Comment by Oluwatiseunla** [comment]
To solve this. Download wget form https://www.gnu.org/software/wget/.
Install the download .exe file and then copy the file to your system 32 folder.
![image](https://github.com/meta-llama/llama/assets/83817282/b0dec7d7-3bd7-424b-96be-f35c45fde369)
