### ISSUE TITLE
No Confirmation Response for Llama2 Access. Request Made Several Days Ago

### ISSUE THREAD

**Issue by oscardam67** [meta-llama/llama#844]
Hi,
I filled out the license form on Meta's website for access to the Llama2 model as instructed on the website. However, I have not received any confirmation or permission so far. I would like to know if my request got through and is being processed, or if there's something else I need to do to get access, especially since it has been nearly 2 weeks since the request.
Thanks for any help.

**Comment by samuelselvan** [comment]
@oscardam67 I would be getting back soon. Thanks!

**Comment by samuelselvan** [comment]
@oscardam67 / @atkallie - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

**Comment by oscardam67** [comment]
> @oscardam67 / @atkallie - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

Hi @samuelselvan, in my case the request ID is: 31543082444058. 
Thank you

**Comment by samuelselvan** [comment]
Apologies for the delay. Am taking a look at this and will get back.

**Comment by samuelselvan** [comment]
Could you all please re-request? https://llama.meta.com/llama-downloads
