### ISSUE TITLE
Response for Llama2 Access

### ISSUE THREAD

**Issue by joseortizm** [meta-llama/llama#861]
Hi! I submitted the request to access Llama-2 but I got no response. I'm working on a research about NLP, Can you help me?

**Comment by subramen** [comment]
@samuelselvan - can you take a look, please?

**Comment by joseortizm** [comment]
Thanks @subramen , @samuelselvan hi! Can you help me? I completed the form. Do you need my email?

**Comment by joseortizm** [comment]
Hello @subramen , can you help me?

**Comment by samuelselvan** [comment]
@joseortizm could you please send me the "Request ID: <>" that gets displayed after you submit the request?

**Comment by joseortizm** [comment]
> @joseortizm could you please send me the "Request ID: <>" that gets displayed after you submit the request?

Hi @samuelselvan ! I can't find. My email is jose.ortiz.m@utec.edu.pe
it is this?
GatedRepoError: 403 Client Error. (Request ID: Root=1-65405c31-6c97fd2a64a39c060ab211eb;b2425c7e-37d4-4208-93dd-5edaa0e55e78)

**Comment by joseortizm** [comment]
Hi @samuelselvan ! can you help me? pls

**Comment by samuelselvan** [comment]
@joseortizm Can you please create a new request and retry? https://llama.meta.com/llama-downloads

**Comment by samuelselvan** [comment]
Please re-open if still needed.
