### ISSUE TITLE
Llama 2 checkpoint request no longer sending download link email

### ISSUE THREAD

**Issue by lisaalaz** [meta-llama/llama#886]
Hi, 

Myself and other PhD students in my department are no longer receiving a download link email after requesting Llama 2 access through the form. We use our academic email address and up until ~3 days ago the email would be sent within seconds. 
We need a different model size which we hadn't downloaded before, hence why the new request, but no link is being sent anymore. Have tried for a couple of days now.
Is the request form currently having issues?

Thanks!

**Comment by samuelselvan** [comment]
@lisaalaz could you please send me the "Request ID: <>" that gets displayed after you submit the request?

**Comment by lisaalaz** [comment]
Hi, thanks, I sent a new request just now and got Request ID: 247403334656843

From: samuelselvan ***@***.***>
Date: Monday, 30 October 2023 at 20:41
To: facebookresearch/llama ***@***.***>
Cc: Alazraki, Lisa ***@***.***>, Mention ***@***.***>
Subject: Re: [facebookresearch/llama] Llama 2 checkpoint request no longer sending download link email (Issue #886)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



@lisaalaz<https://github.com/lisaalaz> could you please send me the "Request ID: <>" that gets displayed after you submit the request?

**Comment by lisaalaz** [comment]
Hi, thanks, I sent a new request just now and got Request ID: 247403334656843

**Comment by Abhiram4572** [comment]
Hey, even I have filled the form but haven't received any download link, can you please help me with it?
Request ID: 1361948751363309

**Comment by WieMaKa** [comment]
Hello I am waiting now already over 48 hours to get a link via Meta (Request ID: 843428860670466) or HF

<img width="568" alt="image" src="https://github.com/facebookresearch/llama/assets/66131143/be33af4f-26b5-47c6-86a0-b87b89f3fd5e">

It is my first to to request over HF. But for Meta I requested it previously with the same email address and received it within 10 mins.

**Comment by samuelselvan** [comment]
Apologies for the delay. Could you please retry?

**Comment by samuelselvan** [comment]
Please feel free to re-open with the new request id? We did push few changes to help situations like this. Thanks

https://llama.meta.com/llama-downloads
