### ISSUE TITLE
Renewing model download fails

### ISSUE THREAD

**Issue by justinwiley** [meta-llama/llama#980]
**Before submitting a bug, please make sure the issue hasn't been already addressed by searching through the [FAQs](https://ai.meta.com/llama/faq/) and [existing/past issues](https://github.com/facebookresearch/llama/issues)**

## Describe the bug
I was previously approved for download access, when downloading using the link, it returns 403.  I've resubmitted the form, but now I'm getting "Sorry, you are not eligible to access Llama 2."

Can you tell me why I'm no longer eligible?

**Comment by samuelselvan** [comment]
@justinwiley - can you please send a screenshot of the error message?

https://ai.meta.com/resources/models-and-libraries/llama-downloads/

Also if you have submitted, can you please send the request id that gets displayed after confirmation?
