### ISSUE TITLE
unable to receive emails from Meta for downloading the mode

### ISSUE THREAD

**Issue by AnandUgale** [meta-llama/llama#981]
I have been unable to receive emails from Meta for downloading the model, despite attempting with multiple email addresses. Could someone please suggest what steps I should take next?

**Comment by samuelselvan** [comment]
@AnandUgale - can you please share the request id you get after submitting the request?

**Comment by AnandUgale** [comment]
Request ID: 324720877204138

**Comment by samuelselvan** [comment]
@AnandUgale - am taking a look now. Let me get back.

**Comment by samuelselvan** [comment]
@AnandUgale - apologies for the delay. Sorry do you mind submitting one more request and re-open if you still face issues?
